CI

diff --git a/.github/workflows/ci-windows.yml b/.github/workflows/ci-windows.yml
--- a/.github/workflows/ci-windows.yml
+++ b/.github/workflows/ci-windows.yml
@@ -13,38 +13,13 @@ jobs:
     - run: git config --global core.autocrlf input
     - uses: actions/checkout@v5
 
-    - name: Download and extract omnirig
+    - name: Download and extract OmniRig
       run: |
         # Download the zip file
         Invoke-WebRequest -Uri "http://dxatlas.com/OmniRig/Files/OmniRig.zip" -OutFile "OmniRig.zip"
         
         # Extract the zip
         Expand-Archive -Path "OmniRig.zip" -DestinationPath "installer" -Force
-      shell: pwsh
-
-    - name: Download and extract omnirig
-      run: |        
-        .\installer\OmniRigSetup.exe /S /silent /quiet
-        
-        $cmd = ".\installer\OmniRigSetup.exe /S /silent /quiet"
-        $exitCode = Invoke-Command -ScriptBlock { cmd /c $cmd *> $null; return $LASTEXITCODE }
-        
-        if ($exitCode -ne 0) {
-        Write-Host "*** Error: Installer returned exit code $exitCode ***"
-        exit 1
-        } else {
-        Write-Host "  --> OmniRig Installation Completed."
-        }
-
-
-        # Verify installation
-        $pathTest = "$env:PROGRAMFILES (x86)\Afreet\Omnirig\omnirig.exe"
-        if (Test-Path $pathTest) {
-        Write-Host "  --> OmniRig Installer indicated successful deployment"
-        } else {
-        Write-Host "*** Install failed. Expected file not found at: $pathTest ***"
-        exit 1
-        }
       shell: pwsh
 
     - uses: msys2/setup-msys2@v2
@@ -95,6 +70,29 @@ jobs:
         mv 'D:/a/salyh/wsjt-wsjtx-2m-buildtest/local/hamlib465-tmp/hamlib-w64-4.6.5' 'D:/a/salyh/wsjt-wsjtx-2m-buildtest/local/hamlib'
         mv 'D:/a/salyh/wsjt-wsjtx-2m-buildtest/local/hamlib/lib/gcc/libhamlib.dll.a' 'D:/a/salyh/wsjt-wsjtx-2m-buildtest/local/hamlib/lib/libhamlib.dll.a'
 
+    - name: Install OmniRig
+      shell: msys2 {0}
+      run: |
+        # Run the installer
+        ./installer/OmniRigSetup.exe /S /silent /quiet
+        exitCode=$?
+        
+        if [ $exitCode -ne 0 ]; then
+          echo "*** Error: Installer returned exit code $exitCode ***"
+          exit 1
+        else
+          echo "  --> OmniRig Installation Completed."
+        fi
+        
+        # Verify installation
+        pathTest="/c/Program Files (x86)/Afreet/Omnirig/omnirig.exe"
+        if [ -f "$pathTest" ]; then
+          echo "  --> OmniRig Installer indicated successful deployment"
+        else
+          echo "*** Install failed. Expected file not found at: $pathTest ***"
+          exit 1
+        fi
+      
     - name: Configure
       shell: msys2 {0}
       run: |
